Repository canonical/microk8s.io, pull requests merged in 2018-11, with the labels that each got.

#23 Sass and JS building infrastructure
  .circleci/config.yml
  _sass/styles.scss
  index.new.html
  js/global-nav.js
  package.json
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#30 Microk8s homepage refresh 19
  _sass/styles.scss
  index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#32 Minimise bespoke css, fix markup and update styling
  _sass/_settings.scss
  _sass/styles.scss
  index.html
  index.new.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#33 Add metatage for mobile viewports
  index.html
Labels: Review: QA +1

#31 Includes Docs at /docs
  README.md
  _layouts/base.html
  _layouts/docs.html
  _sass/_blockquote.scss
  _sass/_settings.scss
  _sass/_sidebar.scss
  _sass/styles.scss
  docs/dockerd.md
  docs/index.md
  docs/registry.md
  docs/release-channels.md
  index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#42 Accessibiliy fixes
  _sass/styles.scss
  index.html
Labels: Review: Code +1, Review: QA +1

#41 Improve performance
  _layouts/base.html
  package.json
Labels: Review: Code +1, Review: QA +1

#38 Remove all legacy files
  assets/css/bootstrap.css
  assets/css/main.css
  assets/fonts/glyphicons-halflings-regular.eot
  assets/fonts/glyphicons-halflings-regular.svg
  assets/fonts/glyphicons-halflings-regular.ttf
  assets/fonts/glyphicons-halflings-regular.woff
  assets/img/card.jpg
  assets/img/fast.png
  assets/img/kubee.png
  assets/img/secure.png
  assets/js/bootstrap.min.js
Labels: Review: QA +1

#37 Validated the homepage
  _layouts/base.html
  index.html
Labels: Review: Code +1, Review: QA +1

#39 Bump the versio nof Jekyll to v3.6.3
  Gemfile
  Gemfile.lock
Labels: Review: Code +1, Review: QA +1

#46 Highlight docs when in docs
  _layouts/base.html
  _sass/_sidebar.scss
Labels: Review: Code +1, Review: QA +1

#45 Convert the links in the docs to true links
  docs/dockerd.md
  docs/index.md
  docs/registry.md
Labels: Review: Code +1, Review: UX +1

#47 Update snap store button image
  index.html
Labels: Review: Code +1, Review: QA +1

#48 Surely we should link to /docs?
  index.html
Labels: Review: Code +1
