Repository canonical/microk8s.io, pull requests merged in 2019-10, with the labels that each got.

#123 reorder head tags
  _layouts/base.html
Labels: Review: Code +1

#124 use optimised "certified kubernetes" SVG
  index.html
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#125 remove trailing slashes from /docs/ sub pages
  _layouts/base.html
  docs/clustering.md
  docs/ports.md
  docs/release-channels.md
  docs/working.md
  index.html
Labels: Review: Code +1, Review: QA +1

#120 Link to clustering
  _layouts/docs.html
Labels: Review: QA needed

#126 increase site speed analytics sampling
  _layouts/base.html
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#128 Remove capital letter from command
  index.html
Labels: Review: Code +1, Review: QA +1

#121 Add addons page
  _layouts/docs.html
  docs/addons.md
Labels: Review: Code +1, Review: QA +1

#130 Add lazysizes
  _layouts/base.html
  index.html
  package.json
  yarn.lock
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#131 Add never pull image when working without registry
  docs/working.md
Labels: Review: QA +1

#134 suggested wording
  docs/index.md
Labels: Review: Code +1

#132 Add fluentd page
  docs/addon-fluentd.md
  docs/addons.md
Labels: Review: Code +1, Review: QA +1

#135 Add addons for dns,dashboard,gpu
  docs/addon-dashboard.md
  docs/addon-dns.md
  docs/addon-gpu.md
  docs/addons.md
Labels: Review: Code +1, Review: QA +1

#137 Add release-notes page
  _layouts/docs.html
  docs/release-notes.md
Labels: Review: Code +1, Review: QA +1

#138 Add command reference
  _layouts/docs.html
  docs/commands.md
Labels: Review: Code +1, Review: QA +1

#133 Add linkerd addon docs
  docs/addon-linkerd
  docs/addons.md
Labels: Review: Code +1, Review: QA +1

#141 [Docs] Add get in touch page
  _layouts/docs.html
  docs/get-in-touch.md
Labels: Review: Code +1, Review: QA +1

#142 Added .dockerignore
  .dockerignore
Labels: Review: Code needed

#140 [Docs] Adds pages for configuring the systemd services run by MicroK8s
  _layouts/docs.html
  docs/configuring-services.md
Labels: Don't merge, Review: Code +1, Review: QA +1
