Repository canonical/microk8s.io, pull requests merged in 2019-09, with the labels that each got.

#109 microk8s homepage - improve the ticked list design
  index.html
Labels: Review: Code +1, Review: QA +1

#111 Update text, add GitHub buttons
  _layouts/base.html
  index.html
Labels: Review: Code +1, Review: QA +1

#114 Update banner
  _sass/styles.scss
  index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#117 Services and auth rework
  docs/ports.md
Labels: Review: Code +1, Review: QA needed

#113 [microk8s documentation] Documentation on clustering available with the 1.16 release
  docs/clustering.md
Labels: Review: Code +1, Review: QA +1

#118 fixed link
  docs/ports.md
Labels: Released ✈️, Review: Code +1, Review: QA +1
