Repository canonical/microk8s.io, pull requests merged in 2019-11, with the labels that each got.

#144 Remove mentioning of kubenet
  docs/index.md
Labels: Review: Code +1, Review: QA +1

#143 Fix typo on configuring services page
  docs/configuring-services.md
Labels: Review: Code +1, Review: QA +1

#147 Fix path to certs
  docs/ports.md
Labels: Review: Code +1, Review: QA +1

#139 [Docs] Rework channels info and update, adding snap refresh details.
  _layouts/docs.html
  docs/release-channels.md
  docs/setting-snap-channel.md
Labels: Review: Code +1, Review: QA +1

#148 [Docs] Add alternative install page
  _layouts/docs.html
  docs/install-alternatives.md
Labels: Review: Code +1, Review: QA +1

#149 [Docs] Add troubleshooting page
  _layouts/docs.html
  docs/troubleshooting.md
Labels: Review: Code +1, Review: QA +1

#150 remove irc reference
  docs/get-in-touch.md
Labels: Review: Code +1, Review: QA +1

#152 [Docs] Add contributing section
  _layouts/docs.html
  docs/get-in-touch.md
Labels: Review: Code +1, Review: QA +1

#151 [Docs] Fix broken link
  docs/index.md
Labels: Review: Code +1, Review: QA +1

#154 Add quickstart section
  _layouts/docs.html
  docs/index.md
Labels: Review: Code needed, Review: QA needed

#136 Add registry docs category
  _layouts/docs.html
  docs/registry-built-in.md
  docs/registry-images.md
  docs/registry-private.md
  docs/registry-public.md
  docs/working.md
Labels: Don't merge, Review: Code +1, Review: QA +1

#156 [Docs] Add new navigation
  _layouts/docs.html
  docs/addons.md
  docs/install-alternatives.md
  docs/ports.md
Labels: Review: Code +1, Review: QA +1

#157 [Docs] Add feedback links to bottom of pages
  docs/addon-dashboard.md
  docs/addon-dns.md
  docs/addon-fluentd.md
  docs/addon-gpu.md
  docs/addon-linkerd.md
  docs/addons.md
  docs/clustering.md
  docs/commands.md
  docs/configuring-services.md
  docs/get-in-touch.md
  docs/index.md
  docs/install-alternatives.md
  docs/ports.md
  docs/registry-built-in.md
  docs/registry-images.md
  docs/registry-private.md
  docs/registry-public.md
  docs/release-notes.md
  docs/setting-snap-channel.md
  docs/troubleshooting.md
Labels: Review: Code +1, Review: QA +1

#158 [Docs] Fix typo/rendering issue
  docs/index.md
Labels: Review: Code +1, Review: QA +1

#160 Update addon-fluentd.md
  docs/addon-fluentd.md
Labels: Review: Code +1

#162 Proper tabs size
  docs/troubleshooting.md
Labels: Review: Code +1

#163 [Docs] Update file location in ports.md
  docs/ports.md
Labels: Review: Code +1

#164 Revamp install journey
  _sass/styles.scss
  index.html
  js/copytoclipboard.js
  js/installversion.js
  js/tabs.js
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#167 Add KubeCon19 banner
  _sass/styles.scss
  index.html
Labels: Review: Code +1, Review: QA +1

#169 Update index.html
  index.html
Labels: Review: Code +1

#168 Adding MetalLB addon
  docs/addons.md
Labels: Review: Code +1, Review: QA +1

#174 Multipass exec mk8s
  index.html
Labels: Review: Code needed, Review: QA needed

#161 Pointing to the right refresh scheduling location
  docs/setting-snap-channel.md
Labels: Docs 📚

#175 Remove kubecon notice
  index.html
Labels: Review: Code +1, Review: QA +1

#176 Tweaks to quick start/multipass
  docs/index.md
  docs/install-alternatives.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#179 Update misspelled word in docs
  docs/index.md
Labels: Review: QA +1

#184 Update dashboard docs for in-VM setups
  docs/addon-dashboard.md
Labels: Docs 📚, Review: Code +1, Review: QA +1
