Repository canonical/microk8s.io, pull requests merged in 2020-10, with the labels that each got.

#335 Rebuild microk8s home page
  templates/base_layout.html
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#334 Add new cookie policy
  .webpack/entry.js
  package.json
  static/js/cookie-policy.js
  static/sass/styles.scss
  templates/base_layout.html
  templates/partial/_footer.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#346 Remove suru hero
  templates/features/features_layout.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#347 Build tutorials page
  static/sass/_pattern_tutorials.scss
  static/sass/styles.scss
  templates/partial/_navigation.html
  templates/tutorials/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#350 Update video hero section
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#349 Update tutorials difficulty ratings and fix typo
  templates/tutorials/index.html
Labels: Review: Code +1, Review: QA +1

#353 Set the title of the docs pages
  templates/docs/document.html
Labels: Review: Code +1, Review: QA +1
