Repository canonical/microk8s.io, pull requests merged in 2020-06, with the labels that each got.

#278 Initial rebuild of microk8s homepage for v1
  .gitignore
  js/build/global-nav/global-nav.js
  js/build/lazysizes/lazysizes.min.js
  static/js/forms.min.js
  static/js/installversion.js
  static/js/tabs.js
  static/sass/_pattern_github_buttons.scss
  static/sass/_pattern_tiles.scss
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/base_layout.html
  templates/contact-us.html
  templates/index.html
  templates/partial/_footer.html
  templates/partial/_get-started-linux.html
  templates/partial/_get-started-macos.html
  templates/partial/_get-started-windows.html
  templates/partial/_github-buttons.html
  templates/partial/_navigation.html
  templates/thank-you.html
  webapp/app.py
  webpack.config.js
Labels: Review: Code +1, Review: QA +1

#287 Tighten fold area
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#286 Redirect /install.exe to /install/v2.0.0.exe
  .gitignore
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#290 fix unexpected item in text area
  templates/index.html
Labels: Review: Code +1

#293 Update Discourse link
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#292 Update discourse URL to use discuss.kubernetes.io
  requirements.txt
  templates/contact-us.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#294 Update content
  .prettierrc
  .stylelintrc
  package.json
  static/js/tabs.js
  static/sass/styles.scss
  templates/index.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#289 Update webpack config
  .eslintrc.js
  .github/workflows/pr.yml
  .webpack/entry.js
  .webpack/rules.js
  package.json
  static/js/sample.test.js
  webpack.config.js
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#295 Replace quote
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#296 Add k8s configuration in deploy/site.yaml
  README.md
  deploy/site.yaml
Labels: Review: Code +1
