Repository canonical/microk8s.io, pull requests merged in 2020-09, with the labels that each got.

#315 Update 'Join the community' url
  templates/partial/_get-started-windows.html
Labels: Review: Code +1, Review: QA +1

#317 Update the site content
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#319 Remove datasheet from banner
  .github/workflows/pr.yml
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#320 Update flask-base
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#322 Use webteam default renovate config
  renovate.json
Labels: Review: Code +1
