Repository canonical/microk8s.io, pull requests merged in 2020-04, with the labels that each got.

#228 Ask users to gain access to ~/.kube dir
  docs/index.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#242 remove js class rewriting download link
  index.html
Labels: Docs 📚, Review: Code +1, Review: QA +1

#244 Update text and add back missing js files
  index.html
  js/copytoclipboard.js
  js/installversion.js
  js/tabs.js
Labels: Review: Code +1, Review: QA +1

#251 revert install instructions for macOS/Windows
  docs/install-alternatives.md
  index.html
Labels: Docs 📚, Review: Code +1, Review: QA +1

#259 Remote access explanation
  docs/ports.md
Labels: Review: Code +1

#260 Disable renovate for ruby
  renovate.json
Labels: Review: Code +1
