Repository canonical/microk8s.io, pull requests merged in 2020-01, with the labels that each got.

#201 Update release-notes.md
  docs/release-notes.md
Labels: Review: Code +1

#199 Fix the copy functionality in the docs
  _layouts/docs.html
Labels: Review: Code +1, Review: QA +1

#204 Update addons.md
  docs/addons.md
Labels: Review: Code +1, Review: QA +1

#206 Fix URL in addon-dashboard.md
  docs/addon-dashboard.md
Labels: Review: Code +1

#209 Update addons.md
  docs/addons.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#213 Add a variable for the date in the footer's copyright
  _layouts/docs.html
  index.html
Labels: Review: Code +1, Review: QA +1

#214 Add issue and pull request templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review: Code needed, Review: QA needed

#215 update current version refs to 1.17
  docs/index.md
  docs/install-alternatives.md
  docs/setting-snap-channel.md
Labels: Docs 📚, Review: Code +1, Review: QA +1

#216 Move browser test to issue template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Review: QA +1

#217 Copy change on microk8s.io
  index.html
Labels: Review: Code +1, Review: QA +1
