Repository canonical/microk8s.io, pull requests merged in 2020-05, with the labels that each got.

#261 Update the arguments of add-node and status commands
  docs/commands.md
Labels: Docs 📚, Review: Code needed, Review: QA needed

#263 Update homepage to match latest copy
  .circleci/config.yml
  .stylelintrc.json
  package.json
  static/js/base.js
  static/sass/_blockquote.scss
  static/sass/_docs.scss
  static/sass/_sidebar.scss
  static/sass/styles.scss
  templates/_layout.html
  templates/index.html
  templates/partial/_footer.html
  templates/partial/_navigation.html
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#266 Fix typo
  docs/addon-dashboard.md
Labels: Review: Code +1, Review: QA +1

#269 Update tweet text in twitter button
  templates/partial/_navigation.html
Labels: Review: Code +1, Review: QA +1

#265 VM in windows like https://microk8s.io/
  docs/addon-dashboard.md
Labels: Docs 📚

#275 Fix broken JS install tabs
  .gitignore
  static/js/dist/global-nav.js
  static/js/dist/main.js
  static/js/installversion.js
  static/js/tabs.js
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#277 Fix Python dependencies issue
  Dockerfile
Labels: Review: Code +1, Review: QA +1
