Repository canonical/microk8s.io, pull requests merged in 2021-12, with the labels that each got.

#459 Add new microk8s tutorial
  templates/tutorials/index.html
Labels: Review: Code needed, Review: QA needed

#461 Move M1 tutorial to bottom of the tutorial list
  templates/tutorials/index.html
Labels: Review: QA +1, Review: Code +1

#462 Fix hidden elements
  templates/docs/document.html
Labels: Review: QA +1, Review: Code +1

#463 Add localhost links to link ignore
  scripts/linkcheckerrc
Labels: Review: Code +1

#466 Fix embeded video
  templates/index.html
Labels: Review: QA +1, Review: Code +1

#467 Disable linkchecker
  .github/workflows/docs-links.yaml
Labels: Review: Code +1

#468 Update tutorials
  templates/tutorials/index.html
Labels: Review: QA +1, Review: Code +1
