Repository canonical/microk8s.io, pull requests merged in 2022-04, with the labels that each got.

#518 Create /isv contact-us form
  templates/isv/contact-us.html
  templates/isv/index.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#522 Update form-id for /isv contact-us form
  templates/isv/contact-us.html
Labels: Review: QA +1, Review: Code +1

#523 Copy update on /tutorials
  templates/tutorials/index.html
Labels: Review: QA +1, Review: Code +1

#520 Update index page according to doc
  templates/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#526 Fix typo on index
  templates/index.html
Labels: Review: Code +1

#527 Update asset on /resources
  templates/resources/index.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#530 Add link to addon howto
  templates/index.html
Labels: Review: QA +1, Review: Code +1
