Repository canonical/microk8s.io, pull requests merged in 2022-01, with the labels that each got.

#489 Revert "Disable linkchecker"
  .github/workflows/docs-links.yaml
Labels: Review: Code +1

#453 Update to Vanilla 3.0
  js/build/global-nav/global-nav.js
  package.json
  run
  static/sass/_blockquote.scss
  static/sass/_pattern_tiles.scss
  static/sass/_sidebar.scss
  static/sass/styles.scss
  templates/404.html
  templates/500.html
  templates/contact-us.html
  templates/docs/document.html
  templates/docs/search.html
  templates/features/features_layout.html
  templates/features/high-availability.html
  templates/index.html
  templates/partial/_get-started-linux.html
  templates/partial/_get-started-macos.html
  templates/partial/_navigation.html
  templates/thank-you.html
  templates/tutorials/index.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)

#495 Build /compare page
  templates/compare/index.html
  templates/partial/_navigation.html
  webapp/app.py
Labels: Review: QA +1, Review: Code +1

#497 Update marketo endpoint
  templates/contact-us.html
Labels: Review: QA +1, Review: Code +1

#499 Tiny typo
  templates/compare/index.html
Labels: Review: QA +1, Review: Code +1
