Repository canonical/microk8s.io, pull requests merged in 2023-10, with the labels that each got.

#624 Update to new documentation layout
  package.json
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/base_layout.html
  templates/docs/document.html
  templates/partial/_footer.html
  templates/partial/_navigation.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Review: Design +1, Docs 📚

#626 Bump canonicalwebteam.discourse to 5.4.3
  requirements.txt
Labels: Review: QA +1, Review: Code +1

#625 /resources - Add thumbnails, embed videos
  templates/resources/videos-and-webinars.html
Labels: Review: QA +1, Review: Code +1, Review: Design +1, Review: UX +1
